### ISSUE TITLE
Update to PhantomJS 2.1.1

### ISSUE THREAD

**Issue by ocombe** [gskachkov/phantomjs2#13]
Hello, phantomjs 2.1.1 has been released, can you update the repo to download it ? The binaries are here: https://bitbucket.org/ariya/phantomjs/downloads/

**Comment by gskachkov** [comment]
@ocombe  Thanks. I'll tried to update link soon!

**Comment by ocombe** [comment]
\o/
Thanks !

**Comment by gskachkov** [comment]
@ocombe Ohhh, sorry. 
Now I'm fully focused on contributing to the WebKit, and quite hard to me find some time to fix issues in this project.
