### ISSUE TITLE
ERROR [launcher]: Cannot start PhantomJS2

### ISSUE THREAD

**Issue by mdix** [gskachkov/phantomjs2#7]
Hi,

thanks for creating this package.

When trying to run phantomjs2 via karma & karma-phantomjs2-launcher **on travis**, I always get the above mentioned error. The project I try to build is [this](https://github.com/mdix/es6-babel-browserify-karma-boilerplate/). You can see the build output [here](https://travis-ci.org/mdix/es6-babel-browserify-karma-boilerplate/jobs/84700082). 

Thanks for your help.

Best
Marc

**Comment by gskachkov** [comment]
I'll try to take look during this week. At first look there can be some problem with version of PhantomsJS, because there were build Phantom for only Win/Mac/Ubuntu. Possible karma launcher mismatch version of OS.

**Comment by mdix** [comment]
Ok, thanks. If you think that I can help you somehow, please let me know.

**Comment by mdix** [comment]
Hey @gskachkov,

any news on this?

Best
Marc

**Comment by mdix** [comment]
Hey @gskachkov,

hope you're alright. Any news?

Best
Marc

**Comment by gskachkov** [comment]
@mdix Ohh, sorry. I'm have been working on patch for WebKit for last 4 weeks. Now it uploaded for review so I can spend more time on another thinks. 
Now I'l try to help you

**Comment by gskachkov** [comment]
@mdix I've managed to build your project, and run tests with phantomjs2
If you are using [special version of the PhantomJS for travis ubuntu 12.04](https://github.com/mdix/es6-babel-browserify-karma-boilerplate/blob/master/.travis.yml#L3), you need to set path to custom PhantomJS in env variables, for instance 
_export PHANTOMJS_BIN=/usr/local/phantomjs/bin/phantomjs_
You can add this value to configuration of travis build or add as the command to _.travis.yml_
See my [build log](https://travis-ci.org/gskachkov/es6-babel-browserify-karma-boilerplate/jobs/87359137#L80) of your project. 
My version of phantomjs2 installer doesn't support Ubunt 12.04, only 14.xx. 
And sorry for late answer.

**Comment by mdix** [comment]
@gskachkov YAY nice, working. Thanks. I knew that but I shomehow must've missed this little detail. Thanks for your help.

**Comment by gskachkov** [comment]
Nice to hear!
